In [16]:
import matplotlib.pyplot as plt
import pandas as pd
import hvplot.pandas
import numpy as np

In [17]:
abs_data = pd.read_csv("cattle_totals_2020.csv")

In [18]:
abs_data

,Table,13.1,13.1.1,13.1.2,13.1.3,13.1.4,13.2,13.2.1,13.2.2,13.2.3,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
0,Activity 1,Slaughter,Slaughter weight,Production,Exports (inc reexports),Consumption,Closing inventory,Closing inventory,Closing inventory,Closing inventory,...,Production,Production,Production,Production,Production,Production,Production,Production,Production,Production
1,Activity 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Commodity,Total,Total,Beef and veal,Beef and veal,Beef and veal,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,Australia,Australia,Australia,Australia,Australia,New South Wales,Victoria,Queensland,South Australia,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
4,Location,NaN,NaN,NaN,World,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Measure,Head/number,Quantity,Quantity,Quantity,Quantity,Head/number,Head/number,Head/number,Head/number,...,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity
6,Unit,'000,kg,kt,kt,kt,'000,'000,'000,'000,...,kt,kt,kt,kt,kt,kt,kt,kt,kt,kt
7,Frequency,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,...,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year
8,Notes,"a,1","1, 2","1,2","a, 3","a,1,2,3",4,4,4,4,...,"c,6",6,6,6,6,6,6,6,6,6
9,Series Start,1972,1972,1972,1972,1972,1982,1982,1982,1982,...,1972,1972,1972,1972,1994,1986,1972,1972,1972,1972
10,Series End,2018,2018,2018,2018,2018,2018,2018,2018,2018,...,2018,2018,2018,2018,2013,2018,2018,2018,2018,2018
11,Identifier,AG351,AG5836,AG356,AB23352,AG7325,AG1265,AG1267,AG1271,AG1273,...,AG7302,AG1416,AG1417,AG1239,AG7863,AG1421,AG1426,AG1196,AG1431,AG1435
12,1974,8452.40,183.02,1546.96,611.20,881.00,NaN,NaN,NaN,NaN,...,187,292,700,405,NaN,NaN,527,10715,320,38235
13,1975,10617.50,173.34,1840.42,800.20,936.00,NaN,NaN,NaN,NaN,...,604,353,1038,508,NaN,NaN,492,11271,345,41597
14,1976,11982.00,165.90,1987.78,936.80,976.00,NaN,NaN,NaN,NaN,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,12968.00,168.40,2183.84,1115.30,955.51,NaN,NaN,NaN,NaN,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,11348.00,177.84,2018.11,1216.70,833.68,NaN,NaN,NaN,NaN,...,624,403,1038,562,NaN,NaN,629,11279,354,43541
17,1979,8890.00,175.98,1564.44,864.00,729.00,NaN,NaN,NaN,NaN,...,635,402,1116,512,NaN,NaN,679,9924,266,41773
18,1980,8436.00,173.92,1467.19,767.30,728.00,NaN,NaN,NaN,NaN,...,642,418,1209,496,NaN,NaN,733,9998,336,42921
19,1981,8691.00,181.36,1576.20,783.70,750.00,NaN,NaN,NaN,NaN,...,675,471,1271,498,NaN,NaN,616,10354,407,43232
20,1982,9117.00,169.23,1542.88,827.30,701.00,NaN,NaN,NaN,NaN,...,710,481,1381,521,NaN,NaN,625,10425,383,43332
21,1983,7317.00,183.86,1345.28,703.80,654.00,NaN,NaN,NaN,NaN,...,740,495,1229,536,NaN,NaN,653,10748,412,43428
22,1984,7036.00,186.19,1310.02,611.20,660.00,2583.05,1077.14,4421.61,386.35,...,770,535,1323,433,NaN,NaN,669,10929,295,44481
23,1985,7403.00,187.08,1384.92,712.00,656.00,2672.00,1141.00,4554.00,409.00,...,795,555,1339,486,NaN,NaN,638,10997,342,45492
24,1986,7985.00,190.45,1520.73,844.90,635.00,2629.00,1186.00,4498.00,434.00,...,1631,559,1200,466,NaN,NaN,616,11292,358,47497
25,1987,8112.00,195.73,1587.72,955.90,660.00,2651.00,1195.00,4436.00,445.00,...,1603,565,1205,563,NaN,NaN,583,10884,277,48692
26,1988,7244.00,205.89,1491.48,797.35,684.02,2783.00,1229.00,4488.00,456.00,...,1849,570,1754,562,NaN,3490,553,10880,321,48712
27,1989,7941.00,211.15,1676.72,976.59,687.80,2962.00,1305.00,4754.00,469.00,...,2070,548,2140,550,NaN,3575,582,10633,376,49551
28,1990,8376.00,210.07,1759.57,1084.96,668.36,2961.00,1263.00,5011.00,470.00,...,2161,549,1790,471,NaN,3635,661,10464,349,50466
29,1991,8718.00,205.42,1790.87,1146.07,641.72,2915.00,1254.00,4999.00,458.00,...,1459,574,1580,524,NaN,3350,700,10534,315,50334
30,1992,8479.00,215.33,1825.81,1200.88,622.25,3063.00,1237.00,4964.00,544.00,...,1381,592,1660,518,NaN,3632,745,10613,365,50104
31,1993,8283.00,220.31,1824.80,1186.15,639.29,3243.00,1325.00,4884.00,576.00,...,945,593,1710,575,NaN,2820,691,10584,309,47427
32,1994,8269.00,218.09,1803.42,1148.26,653.70,2910.00,1229.00,4522.00,529.00,...,1025,602,1810,566,NaN,2720,581,11194,368,48177
33,1995,7936.00,219.85,1744.70,1114.29,626.60,2963.00,1287.00,4775.00,534.00,...,1100,601,1850,630,NaN,2295,542,11585,344,49020
34,1996,8411.00,215.23,1810.30,1093.55,714.03,3039.00,1286.00,4957.69,528.00,...,900,555,1800,639,717,2210,525,11749,410,50087
35,1997,9320.00,209.79,1955.25,1250.83,696.65,2863.00,1119.00,5145.40,540.00,...,1100,530,1795,651,827,2010,591,11714,468,51696
36,1998,9099.00,220.96,2010.53,1326.43,674.76,2859.00,1054.00,5071.00,514.00,...,1350,530,1800,605,846,1890,539,11804,454,51767
37,1999,8644.00,229.97,1987.90,1284.17,696.18,2801.00,1134.00,5667.00,480.00,...,1450,537,1900,570,867,1740,584,12124,425,52825
38,2000,8981.00,235.99,2119.43,1460.97,648.63,2849.00,1138.00,5304.00,516.00,...,1525,530,1900,581,886,1595,625,12298,440,53001
39,2001,8589.00,236.07,2027.61,1382.01,638.25,2852.00,1158.00,5762.00,594.00,...,1650,458,1925,577,903,1580,524,11983,317,52210
40,2002,9230.00,224.58,2072.83,1387.60,675.80,2809.00,1240.00,5380.00,590.00,...,1810,537,1725,588,925,1650,573,12427,425,53891
41,2003,8778.00,231.60,2032.94,1319.11,697.41,2873.00,1185.00,5638.00,568.00,...,1960,496,1950,681,953,1680,610,12039,450,54200
42,2004,8853.00,244.21,2161.96,1491.25,661.28,2814.00,1247.00,5844.00,630.00,...,2170,514,1900,697,979,1640,632,11261,544,55493
43,2005,8402.00,247.21,2077.07,1395.47,670.12,2997.00,1272.00,5745.00,591.00,...,2225,500,1725,661,1004,1520,672,11318,600,54138
44,2006,9087.00,245.00,2226.29,1516.82,698.79,2883.00,1218.00,5589.00,527.00,...,2450,497,1550,648,1300,1450,808,11980,640,55823
45,2007,8682.00,245.58,2132.12,1440.19,686.21,2982.00,1206.00,6113.00,533.00,...,2490,504,1600,607,1344,1445,861,12097,560,57037
46,2008,8585.00,247.54,2125.11,1485.29,634.48,2915.00,1092.00,5911.00,543.00,...,2700,520,1667,644,1388,1498,770,12160,535,56841
47,2009,8367.00,252.04,2108.78,1377.35,725.14,2796.00,1016.00,5953.00,489.00,...,2950,518,1705,623,1437,1470,797,11885,580,56848
48,2010,8099.00,263.41,2133.36,1441.83,691.78,2763.07,1119.37,6000.74,523.68,...,3125,515,1745,642,1485,1455,886,12034,530,57190
49,2011,7875.00,268.54,2114.76,1462.15,656.76,3027.54,1248.47,6177.37,633.18,...,3308,500,1804,601,1536,1367,870,11978,510,56727
50,2012,8456.00,265.49,2244.97,1539.35,707.92,2948.46,1101.71,6295.26,603.07,...,3491,519,1821,624,1587,1377,852,11845,530,57009
51,2013,9474.00,260.09,2464.07,1769.37,696.80,2751.92,1096.84,6376.95,567.16,...,3800,508,1807,620,1630,1367,905,11751,525,57911
52,2014,10105.00,263.40,2661.64,2009.07,653.41,2650.35,1104.79,5540.65,513.31,...,4000,502,1827,658,1685,1362,983,11075,555,57649
53,2015,8800.00,266.31,2343.52,1749.43,595.58,2399.77,884.35,5241.94,448.89,...,4080,481,1850,690,1710,1364,1038,10817,565,57543
54,2016,7421.00,278.75,2068.62,1443.39,625.86,2517.18,947.47,5629.31,464.00,...,4170,465,1879,648,NaN,1339,1091,11507,580,55293
55,2017,7915.00,282.71,2237.68,1638.22,596.52,2274.00,965.89,5870.80,433.46,...,4230,469,1925,654,NaN,1325,1046,11943,594,56523
56,2018,8704.00,270.20,2351.79,1771.02,579.06,1864.99,999.11,5743.95,427.07,...,4240,475,1980,672,NaN,1357,1027,12256,596,57810
57,2019,8699.00,272.63,2371.61,1861.44,509.86,1909.74,952.75,5406.26,451.92,...,4270,471,2027,713,NaN,1374,1019,12385,562,58527
58,2020,6621.30,291.88,1932.60,1411.91,525.99,2171.20,1021.24,5624.84,482.51,...,3760,477,2079,727,NaN,1378,1008,12389,520,57658
59,2021,6148.00,305.45,1877.88,1349.60,532.51,NaN,NaN,NaN,NaN,...,4195,480,2129,754,NaN,1380,996,12734,670,58371

In [19]:
abs_data.drop(abs_data.index[0:2],inplace=True)
abs_data.reset_index()
abs_data

,Table,13.1,13.1.1,13.1.2,13.1.3,13.1.4,13.2,13.2.1,13.2.2,13.2.3,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
2,Commodity,Total,Total,Beef and veal,Beef and veal,Beef and veal,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,Australia,Australia,Australia,Australia,Australia,New South Wales,Victoria,Queensland,South Australia,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
4,Location,NaN,NaN,NaN,World,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Measure,Head/number,Quantity,Quantity,Quantity,Quantity,Head/number,Head/number,Head/number,Head/number,...,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity
6,Unit,'000,kg,kt,kt,kt,'000,'000,'000,'000,...,kt,kt,kt,kt,kt,kt,kt,kt,kt,kt
7,Frequency,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,Fiscal Year,...,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year,Calendar Year
8,Notes,"a,1","1, 2","1,2","a, 3","a,1,2,3",4,4,4,4,...,"c,6",6,6,6,6,6,6,6,6,6
9,Series Start,1972,1972,1972,1972,1972,1982,1982,1982,1982,...,1972,1972,1972,1972,1994,1986,1972,1972,1972,1972
10,Series End,2018,2018,2018,2018,2018,2018,2018,2018,2018,...,2018,2018,2018,2018,2013,2018,2018,2018,2018,2018
11,Identifier,AG351,AG5836,AG356,AB23352,AG7325,AG1265,AG1267,AG1271,AG1273,...,AG7302,AG1416,AG1417,AG1239,AG7863,AG1421,AG1426,AG1196,AG1431,AG1435
12,1974,8452.40,183.02,1546.96,611.20,881.00,NaN,NaN,NaN,NaN,...,187,292,700,405,NaN,NaN,527,10715,320,38235
13,1975,10617.50,173.34,1840.42,800.20,936.00,NaN,NaN,NaN,NaN,...,604,353,1038,508,NaN,NaN,492,11271,345,41597
14,1976,11982.00,165.90,1987.78,936.80,976.00,NaN,NaN,NaN,NaN,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,12968.00,168.40,2183.84,1115.30,955.51,NaN,NaN,NaN,NaN,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,11348.00,177.84,2018.11,1216.70,833.68,NaN,NaN,NaN,NaN,...,624,403,1038,562,NaN,NaN,629,11279,354,43541
17,1979,8890.00,175.98,1564.44,864.00,729.00,NaN,NaN,NaN,NaN,...,635,402,1116,512,NaN,NaN,679,9924,266,41773
18,1980,8436.00,173.92,1467.19,767.30,728.00,NaN,NaN,NaN,NaN,...,642,418,1209,496,NaN,NaN,733,9998,336,42921
19,1981,8691.00,181.36,1576.20,783.70,750.00,NaN,NaN,NaN,NaN,...,675,471,1271,498,NaN,NaN,616,10354,407,43232
20,1982,9117.00,169.23,1542.88,827.30,701.00,NaN,NaN,NaN,NaN,...,710,481,1381,521,NaN,NaN,625,10425,383,43332
21,1983,7317.00,183.86,1345.28,703.80,654.00,NaN,NaN,NaN,NaN,...,740,495,1229,536,NaN,NaN,653,10748,412,43428
22,1984,7036.00,186.19,1310.02,611.20,660.00,2583.05,1077.14,4421.61,386.35,...,770,535,1323,433,NaN,NaN,669,10929,295,44481
23,1985,7403.00,187.08,1384.92,712.00,656.00,2672.00,1141.00,4554.00,409.00,...,795,555,1339,486,NaN,NaN,638,10997,342,45492
24,1986,7985.00,190.45,1520.73,844.90,635.00,2629.00,1186.00,4498.00,434.00,...,1631,559,1200,466,NaN,NaN,616,11292,358,47497
25,1987,8112.00,195.73,1587.72,955.90,660.00,2651.00,1195.00,4436.00,445.00,...,1603,565,1205,563,NaN,NaN,583,10884,277,48692
26,1988,7244.00,205.89,1491.48,797.35,684.02,2783.00,1229.00,4488.00,456.00,...,1849,570,1754,562,NaN,3490,553,10880,321,48712
27,1989,7941.00,211.15,1676.72,976.59,687.80,2962.00,1305.00,4754.00,469.00,...,2070,548,2140,550,NaN,3575,582,10633,376,49551
28,1990,8376.00,210.07,1759.57,1084.96,668.36,2961.00,1263.00,5011.00,470.00,...,2161,549,1790,471,NaN,3635,661,10464,349,50466
29,1991,8718.00,205.42,1790.87,1146.07,641.72,2915.00,1254.00,4999.00,458.00,...,1459,574,1580,524,NaN,3350,700,10534,315,50334
30,1992,8479.00,215.33,1825.81,1200.88,622.25,3063.00,1237.00,4964.00,544.00,...,1381,592,1660,518,NaN,3632,745,10613,365,50104
31,1993,8283.00,220.31,1824.80,1186.15,639.29,3243.00,1325.00,4884.00,576.00,...,945,593,1710,575,NaN,2820,691,10584,309,47427
32,1994,8269.00,218.09,1803.42,1148.26,653.70,2910.00,1229.00,4522.00,529.00,...,1025,602,1810,566,NaN,2720,581,11194,368,48177
33,1995,7936.00,219.85,1744.70,1114.29,626.60,2963.00,1287.00,4775.00,534.00,...,1100,601,1850,630,NaN,2295,542,11585,344,49020
34,1996,8411.00,215.23,1810.30,1093.55,714.03,3039.00,1286.00,4957.69,528.00,...,900,555,1800,639,717,2210,525,11749,410,50087
35,1997,9320.00,209.79,1955.25,1250.83,696.65,2863.00,1119.00,5145.40,540.00,...,1100,530,1795,651,827,2010,591,11714,468,51696
36,1998,9099.00,220.96,2010.53,1326.43,674.76,2859.00,1054.00,5071.00,514.00,...,1350,530,1800,605,846,1890,539,11804,454,51767
37,1999,8644.00,229.97,1987.90,1284.17,696.18,2801.00,1134.00,5667.00,480.00,...,1450,537,1900,570,867,1740,584,12124,425,52825
38,2000,8981.00,235.99,2119.43,1460.97,648.63,2849.00,1138.00,5304.00,516.00,...,1525,530,1900,581,886,1595,625,12298,440,53001
39,2001,8589.00,236.07,2027.61,1382.01,638.25,2852.00,1158.00,5762.00,594.00,...,1650,458,1925,577,903,1580,524,11983,317,52210
40,2002,9230.00,224.58,2072.83,1387.60,675.80,2809.00,1240.00,5380.00,590.00,...,1810,537,1725,588,925,1650,573,12427,425,53891
41,2003,8778.00,231.60,2032.94,1319.11,697.41,2873.00,1185.00,5638.00,568.00,...,1960,496,1950,681,953,1680,610,12039,450,54200
42,2004,8853.00,244.21,2161.96,1491.25,661.28,2814.00,1247.00,5844.00,630.00,...,2170,514,1900,697,979,1640,632,11261,544,55493
43,2005,8402.00,247.21,2077.07,1395.47,670.12,2997.00,1272.00,5745.00,591.00,...,2225,500,1725,661,1004,1520,672,11318,600,54138
44,2006,9087.00,245.00,2226.29,1516.82,698.79,2883.00,1218.00,5589.00,527.00,...,2450,497,1550,648,1300,1450,808,11980,640,55823
45,2007,8682.00,245.58,2132.12,1440.19,686.21,2982.00,1206.00,6113.00,533.00,...,2490,504,1600,607,1344,1445,861,12097,560,57037
46,2008,8585.00,247.54,2125.11,1485.29,634.48,2915.00,1092.00,5911.00,543.00,...,2700,520,1667,644,1388,1498,770,12160,535,56841
47,2009,8367.00,252.04,2108.78,1377.35,725.14,2796.00,1016.00,5953.00,489.00,...,2950,518,1705,623,1437,1470,797,11885,580,56848
48,2010,8099.00,263.41,2133.36,1441.83,691.78,2763.07,1119.37,6000.74,523.68,...,3125,515,1745,642,1485,1455,886,12034,530,57190
49,2011,7875.00,268.54,2114.76,1462.15,656.76,3027.54,1248.47,6177.37,633.18,...,3308,500,1804,601,1536,1367,870,11978,510,56727
50,2012,8456.00,265.49,2244.97,1539.35,707.92,2948.46,1101.71,6295.26,603.07,...,3491,519,1821,624,1587,1377,852,11845,530,57009
51,2013,9474.00,260.09,2464.07,1769.37,696.80,2751.92,1096.84,6376.95,567.16,...,3800,508,1807,620,1630,1367,905,11751,525,57911
52,2014,10105.00,263.40,2661.64,2009.07,653.41,2650.35,1104.79,5540.65,513.31,...,4000,502,1827,658,1685,1362,983,11075,555,57649
53,2015,8800.00,266.31,2343.52,1749.43,595.58,2399.77,884.35,5241.94,448.89,...,4080,481,1850,690,1710,1364,1038,10817,565,57543
54,2016,7421.00,278.75,2068.62,1443.39,625.86,2517.18,947.47,5629.31,464.00,...,4170,465,1879,648,NaN,1339,1091,11507,580,55293
55,2017,7915.00,282.71,2237.68,1638.22,596.52,2274.00,965.89,5870.80,433.46,...,4230,469,1925,654,NaN,1325,1046,11943,594,56523
56,2018,8704.00,270.20,2351.79,1771.02,579.06,1864.99,999.11,5743.95,427.07,...,4240,475,1980,672,NaN,1357,1027,12256,596,57810
57,2019,8699.00,272.63,2371.61,1861.44,509.86,1909.74,952.75,5406.26,451.92,...,4270,471,2027,713,NaN,1374,1019,12385,562,58527
58,2020,6621.30,291.88,1932.60,1411.91,525.99,2171.20,1021.24,5624.84,482.51,...,3760,477,2079,727,NaN,1378,1008,12389,520,57658
59,2021,6148.00,305.45,1877.88,1349.60,532.51,NaN,NaN,NaN,NaN,...,4195,480,2129,754,NaN,1380,996,12734,670,58371

In [20]:
abs_data.drop(abs_data.index[4:12],inplace=True)
abs_data

,Table,13.1,13.1.1,13.1.2,13.1.3,13.1.4,13.2,13.2.1,13.2.2,13.2.3,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
2,Commodity,Total,Total,Beef and veal,Beef and veal,Beef and veal,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,Australia,Australia,Australia,Australia,Australia,New South Wales,Victoria,Queensland,South Australia,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
4,Location,NaN,NaN,NaN,World,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Measure,Head/number,Quantity,Quantity,Quantity,Quantity,Head/number,Head/number,Head/number,Head/number,...,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity,Quantity
14,1976,11982.00,165.90,1987.78,936.80,976.00,NaN,NaN,NaN,NaN,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,12968.00,168.40,2183.84,1115.30,955.51,NaN,NaN,NaN,NaN,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,11348.00,177.84,2018.11,1216.70,833.68,NaN,NaN,NaN,NaN,...,624,403,1038,562,NaN,NaN,629,11279,354,43541
17,1979,8890.00,175.98,1564.44,864.00,729.00,NaN,NaN,NaN,NaN,...,635,402,1116,512,NaN,NaN,679,9924,266,41773
18,1980,8436.00,173.92,1467.19,767.30,728.00,NaN,NaN,NaN,NaN,...,642,418,1209,496,NaN,NaN,733,9998,336,42921
19,1981,8691.00,181.36,1576.20,783.70,750.00,NaN,NaN,NaN,NaN,...,675,471,1271,498,NaN,NaN,616,10354,407,43232
20,1982,9117.00,169.23,1542.88,827.30,701.00,NaN,NaN,NaN,NaN,...,710,481,1381,521,NaN,NaN,625,10425,383,43332
21,1983,7317.00,183.86,1345.28,703.80,654.00,NaN,NaN,NaN,NaN,...,740,495,1229,536,NaN,NaN,653,10748,412,43428
22,1984,7036.00,186.19,1310.02,611.20,660.00,2583.05,1077.14,4421.61,386.35,...,770,535,1323,433,NaN,NaN,669,10929,295,44481
23,1985,7403.00,187.08,1384.92,712.00,656.00,2672.00,1141.00,4554.00,409.00,...,795,555,1339,486,NaN,NaN,638,10997,342,45492
24,1986,7985.00,190.45,1520.73,844.90,635.00,2629.00,1186.00,4498.00,434.00,...,1631,559,1200,466,NaN,NaN,616,11292,358,47497
25,1987,8112.00,195.73,1587.72,955.90,660.00,2651.00,1195.00,4436.00,445.00,...,1603,565,1205,563,NaN,NaN,583,10884,277,48692
26,1988,7244.00,205.89,1491.48,797.35,684.02,2783.00,1229.00,4488.00,456.00,...,1849,570,1754,562,NaN,3490,553,10880,321,48712
27,1989,7941.00,211.15,1676.72,976.59,687.80,2962.00,1305.00,4754.00,469.00,...,2070,548,2140,550,NaN,3575,582,10633,376,49551
28,1990,8376.00,210.07,1759.57,1084.96,668.36,2961.00,1263.00,5011.00,470.00,...,2161,549,1790,471,NaN,3635,661,10464,349,50466
29,1991,8718.00,205.42,1790.87,1146.07,641.72,2915.00,1254.00,4999.00,458.00,...,1459,574,1580,524,NaN,3350,700,10534,315,50334
30,1992,8479.00,215.33,1825.81,1200.88,622.25,3063.00,1237.00,4964.00,544.00,...,1381,592,1660,518,NaN,3632,745,10613,365,50104
31,1993,8283.00,220.31,1824.80,1186.15,639.29,3243.00,1325.00,4884.00,576.00,...,945,593,1710,575,NaN,2820,691,10584,309,47427
32,1994,8269.00,218.09,1803.42,1148.26,653.70,2910.00,1229.00,4522.00,529.00,...,1025,602,1810,566,NaN,2720,581,11194,368,48177
33,1995,7936.00,219.85,1744.70,1114.29,626.60,2963.00,1287.00,4775.00,534.00,...,1100,601,1850,630,NaN,2295,542,11585,344,49020
34,1996,8411.00,215.23,1810.30,1093.55,714.03,3039.00,1286.00,4957.69,528.00,...,900,555,1800,639,717,2210,525,11749,410,50087
35,1997,9320.00,209.79,1955.25,1250.83,696.65,2863.00,1119.00,5145.40,540.00,...,1100,530,1795,651,827,2010,591,11714,468,51696
36,1998,9099.00,220.96,2010.53,1326.43,674.76,2859.00,1054.00,5071.00,514.00,...,1350,530,1800,605,846,1890,539,11804,454,51767
37,1999,8644.00,229.97,1987.90,1284.17,696.18,2801.00,1134.00,5667.00,480.00,...,1450,537,1900,570,867,1740,584,12124,425,52825
38,2000,8981.00,235.99,2119.43,1460.97,648.63,2849.00,1138.00,5304.00,516.00,...,1525,530,1900,581,886,1595,625,12298,440,53001
39,2001,8589.00,236.07,2027.61,1382.01,638.25,2852.00,1158.00,5762.00,594.00,...,1650,458,1925,577,903,1580,524,11983,317,52210
40,2002,9230.00,224.58,2072.83,1387.60,675.80,2809.00,1240.00,5380.00,590.00,...,1810,537,1725,588,925,1650,573,12427,425,53891
41,2003,8778.00,231.60,2032.94,1319.11,697.41,2873.00,1185.00,5638.00,568.00,...,1960,496,1950,681,953,1680,610,12039,450,54200
42,2004,8853.00,244.21,2161.96,1491.25,661.28,2814.00,1247.00,5844.00,630.00,...,2170,514,1900,697,979,1640,632,11261,544,55493
43,2005,8402.00,247.21,2077.07,1395.47,670.12,2997.00,1272.00,5745.00,591.00,...,2225,500,1725,661,1004,1520,672,11318,600,54138
44,2006,9087.00,245.00,2226.29,1516.82,698.79,2883.00,1218.00,5589.00,527.00,...,2450,497,1550,648,1300,1450,808,11980,640,55823
45,2007,8682.00,245.58,2132.12,1440.19,686.21,2982.00,1206.00,6113.00,533.00,...,2490,504,1600,607,1344,1445,861,12097,560,57037
46,2008,8585.00,247.54,2125.11,1485.29,634.48,2915.00,1092.00,5911.00,543.00,...,2700,520,1667,644,1388,1498,770,12160,535,56841
47,2009,8367.00,252.04,2108.78,1377.35,725.14,2796.00,1016.00,5953.00,489.00,...,2950,518,1705,623,1437,1470,797,11885,580,56848
48,2010,8099.00,263.41,2133.36,1441.83,691.78,2763.07,1119.37,6000.74,523.68,...,3125,515,1745,642,1485,1455,886,12034,530,57190
49,2011,7875.00,268.54,2114.76,1462.15,656.76,3027.54,1248.47,6177.37,633.18,...,3308,500,1804,601,1536,1367,870,11978,510,56727
50,2012,8456.00,265.49,2244.97,1539.35,707.92,2948.46,1101.71,6295.26,603.07,...,3491,519,1821,624,1587,1377,852,11845,530,57009
51,2013,9474.00,260.09,2464.07,1769.37,696.80,2751.92,1096.84,6376.95,567.16,...,3800,508,1807,620,1630,1367,905,11751,525,57911
52,2014,10105.00,263.40,2661.64,2009.07,653.41,2650.35,1104.79,5540.65,513.31,...,4000,502,1827,658,1685,1362,983,11075,555,57649
53,2015,8800.00,266.31,2343.52,1749.43,595.58,2399.77,884.35,5241.94,448.89,...,4080,481,1850,690,1710,1364,1038,10817,565,57543
54,2016,7421.00,278.75,2068.62,1443.39,625.86,2517.18,947.47,5629.31,464.00,...,4170,465,1879,648,NaN,1339,1091,11507,580,55293
55,2017,7915.00,282.71,2237.68,1638.22,596.52,2274.00,965.89,5870.80,433.46,...,4230,469,1925,654,NaN,1325,1046,11943,594,56523
56,2018,8704.00,270.20,2351.79,1771.02,579.06,1864.99,999.11,5743.95,427.07,...,4240,475,1980,672,NaN,1357,1027,12256,596,57810
57,2019,8699.00,272.63,2371.61,1861.44,509.86,1909.74,952.75,5406.26,451.92,...,4270,471,2027,713,NaN,1374,1019,12385,562,58527
58,2020,6621.30,291.88,1932.60,1411.91,525.99,2171.20,1021.24,5624.84,482.51,...,3760,477,2079,727,NaN,1378,1008,12389,520,57658
59,2021,6148.00,305.45,1877.88,1349.60,532.51,NaN,NaN,NaN,NaN,...,4195,480,2129,754,NaN,1380,996,12734,670,58371

In [21]:
abs_data.drop(abs_data.index[2:4],inplace=True)
abs_data.head()

,Table,13.1,13.1.1,13.1.2,13.1.3,13.1.4,13.2,13.2.1,13.2.2,13.2.3,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
2,Commodity,Total,Total,Beef and veal,Beef and veal,Beef and veal,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,Australia,Australia,Australia,Australia,Australia,New South Wales,Victoria,Queensland,South Australia,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
14,1976,11982.00,165.90,1987.78,936.80,976.00,NaN,NaN,NaN,NaN,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,12968.00,168.40,2183.84,1115.30,955.51,NaN,NaN,NaN,NaN,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,11348.00,177.84,2018.11,1216.70,833.68,NaN,NaN,NaN,NaN,...,624,403,1038,562,NaN,NaN,629,11279,354,43541

In [22]:
abs_data.reset_index()
abs_data.head()

,Table,13.1,13.1.1,13.1.2,13.1.3,13.1.4,13.2,13.2.1,13.2.2,13.2.3,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
2,Commodity,Total,Total,Beef and veal,Beef and veal,Beef and veal,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,Australia,Australia,Australia,Australia,Australia,New South Wales,Victoria,Queensland,South Australia,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
14,1976,11982.00,165.90,1987.78,936.80,976.00,NaN,NaN,NaN,NaN,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,12968.00,168.40,2183.84,1115.30,955.51,NaN,NaN,NaN,NaN,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,11348.00,177.84,2018.11,1216.70,833.68,NaN,NaN,NaN,NaN,...,624,403,1038,562,NaN,NaN,629,11279,354,43541

In [23]:
abs_data.drop(columns=["13.1", "13.1.1", "13.1.2", "13.1.3", "13.1.4", "13.2", "13.2.1", "13.2.2"], inplace=True)
abs_data

,Table,13.2.3,13.2.4,13.2.5,13.2.6,13.2.7,13.2.8,13.2.9,13.2.10,13.2.11,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
2,Commodity,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Beef cows and heifers,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,South Australia,Western Australia,Tasmania,Northern Territory,Australian Capital Territory,Australia,New South Wales,Victoria,Queensland,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
14,1976,NaN,NaN,NaN,NaN,NaN,NaN,7591.00,3331.00,11036.00,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,NaN,NaN,NaN,NaN,NaN,NaN,6689.00,2881.00,10856.00,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,NaN,NaN,NaN,NaN,NaN,NaN,5844.00,2543.00,10261.00,...,624,403,1038,562,NaN,NaN,629,11279,354,43541
17,1979,NaN,NaN,NaN,NaN,NaN,NaN,5484.00,2643.00,9756.00,...,635,402,1116,512,NaN,NaN,679,9924,266,41773
18,1980,NaN,NaN,NaN,NaN,NaN,NaN,4876.00,2696.00,9359.00,...,642,418,1209,496,NaN,NaN,733,9998,336,42921
19,1981,NaN,NaN,NaN,NaN,NaN,NaN,4855.00,2514.00,9210.00,...,675,471,1271,498,NaN,NaN,616,10354,407,43232
20,1982,NaN,NaN,NaN,NaN,NaN,NaN,4545.20,1920.40,8980.70,...,710,481,1381,521,NaN,NaN,625,10425,383,43332
21,1983,NaN,NaN,NaN,NaN,NaN,NaN,4571.00,1952.40,8782.80,...,740,495,1229,536,NaN,NaN,653,10748,412,43428
22,1984,386.35,820.99,194.57,784.15,6.49,10274.35,4775.30,2016.60,9051.00,...,770,535,1323,433,NaN,NaN,669,10929,295,44481
23,1985,409.00,835.00,203.00,806.00,7.00,10626.00,4971.70,2186.40,9303.50,...,795,555,1339,486,NaN,NaN,638,10997,342,45492
24,1986,434.00,860.00,213.00,821.00,7.00,10648.00,4445.30,2013.70,8674.80,...,1631,559,1200,466,NaN,NaN,616,11292,358,47497
25,1987,445.00,890.00,209.00,798.00,7.00,10632.00,4542.60,2038.00,8503.70,...,1603,565,1205,563,NaN,NaN,583,10884,277,48692
26,1988,456.00,908.00,217.00,807.00,7.00,10895.00,4924.00,2070.80,8682.00,...,1849,570,1754,562,NaN,3490,553,10880,321,48712
27,1989,469.00,882.00,221.00,795.00,7.00,11395.00,5141.70,2223.70,9194.90,...,2070,548,2140,550,NaN,3575,582,10633,376,49551
28,1990,470.00,786.00,224.00,788.00,6.00,11510.00,5310.30,2208.00,9575.20,...,2161,549,1790,471,NaN,3635,661,10464,349,50466
29,1991,458.00,810.00,221.00,771.00,6.00,11434.00,5359.10,2152.20,9730.40,...,1459,574,1580,524,NaN,3350,700,10534,315,50334
30,1992,544.00,880.00,230.00,809.00,7.00,11733.00,5440.00,2225.90,9593.20,...,1381,592,1660,518,NaN,3632,745,10613,365,50104
31,1993,576.00,951.00,245.00,846.00,7.00,12076.00,6127.10,2604.00,9656.10,...,945,593,1710,575,NaN,2820,691,10584,309,47427
32,1994,529.00,946.00,224.00,847.00,7.00,11213.00,5866.80,2659.20,9689.10,...,1025,602,1810,566,NaN,2720,581,11194,368,48177
33,1995,534.00,934.00,233.00,848.00,7.00,11667.00,6019.10,2714.10,9928.30,...,1100,601,1850,630,NaN,2295,542,11585,344,49020
34,1996,528.00,928.00,242.00,891.52,7.00,11879.16,6118.10,2627.00,10123.00,...,900,555,1800,639,717,2210,525,11749,410,50087
35,1997,540.00,964.00,232.00,915.00,5.00,11783.37,5921.70,2305.60,10562.30,...,1100,530,1795,651,827,2010,591,11714,468,51696
36,1998,514.00,948.00,224.00,946.00,5.00,11621.00,5845.60,2179.80,10443.60,...,1350,530,1800,605,846,1890,539,11804,454,51767
37,1999,480.00,1086.00,194.00,913.00,6.00,12282.00,5530.70,2370.60,11502.60,...,1450,537,1900,570,867,1740,584,12124,425,52825
38,2000,516.00,1013.00,201.00,981.00,6.00,12007.00,5786.10,2434.70,11087.60,...,1525,530,1900,581,886,1595,625,12298,440,53001
39,2001,594.00,1013.00,199.00,1069.00,6.00,12652.00,5592.60,2463.00,11283.80,...,1650,458,1925,577,903,1580,524,11983,317,52210
40,2002,590.00,981.00,219.00,1023.00,5.00,12245.00,5419.40,2491.40,10507.40,...,1810,537,1725,588,925,1650,573,12427,425,53891
41,2003,568.00,1049.00,233.00,1019.00,5.00,12570.00,5416.00,2390.20,11244.80,...,1960,496,1950,681,953,1680,610,12039,450,54200
42,2004,630.00,1092.00,238.00,1064.00,5.00,12935.00,5335.10,2540.00,11379.60,...,2170,514,1900,697,979,1640,632,11261,544,55493
43,2005,591.00,1199.00,228.00,1160.00,5.00,13197.00,5862.00,2645.70,11353.90,...,2225,500,1725,661,1004,1520,672,11318,600,54138
44,2006,527.00,1144.00,223.00,1211.00,6.00,12800.00,5609.00,2575.20,11494.90,...,2450,497,1550,648,1300,1450,808,11980,640,55823
45,2007,533.00,1217.00,224.00,1193.00,4.00,13472.00,5330.40,2254.30,11730.60,...,2490,504,1600,607,1344,1445,861,12097,560,57037
46,2008,543.00,1201.00,199.00,1037.00,5.00,12903.00,5533.10,2234.30,12151.40,...,2700,520,1667,644,1388,1498,770,12160,535,56841
47,2009,489.00,1214.00,217.00,1256.00,5.00,12946.00,5107.10,2079.50,11193.30,...,2950,518,1705,623,1437,1470,797,11885,580,56848
48,2010,523.68,1062.30,219.92,1187.80,5.66,12882.53,5383.93,2365.85,12449.63,...,3125,515,1745,642,1485,1455,886,12034,530,57190
49,2011,633.18,1072.16,241.81,1227.51,5.20,13633.23,5497.05,2362.08,11989.53,...,3308,500,1804,601,1536,1367,870,11978,510,56727
50,2012,603.07,1004.59,255.98,1214.93,6.02,13430.02,5593.04,2427.18,12628.33,...,3491,519,1821,624,1587,1377,852,11845,530,57009
51,2013,567.16,1081.30,251.14,1192.41,3.66,13321.36,5325.21,2428.17,12754.97,...,3800,508,1807,620,1630,1367,905,11751,525,57911
52,2014,513.31,1228.17,215.81,1274.02,3.96,12531.07,5278.78,2300.61,11178.49,...,4000,502,1827,658,1685,1362,983,11075,555,57649
53,2015,448.89,982.07,180.95,1309.98,3.56,11451.51,4674.55,1819.06,10390.12,...,4080,481,1850,690,1710,1364,1038,10817,565,57543
54,2016,464.00,1087.70,214.45,1312.67,3.44,12176.21,4992.27,1980.66,10992.60,...,4170,465,1879,648,NaN,1339,1091,11507,580,55293
55,2017,433.46,1033.82,195.58,1377.51,3.53,12154.90,4425.55,2064.21,11909.95,...,4230,469,1925,654,NaN,1325,1046,11943,594,56523
56,2018,427.07,1068.17,197.98,1376.89,1.95,11680.11,3780.35,2106.24,11156.29,...,4240,475,1980,672,NaN,1357,1027,12256,596,57810
57,2019,451.92,1087.91,243.46,1087.54,1.27,11140.85,3602.63,2045.37,10381.26,...,4270,471,2027,713,NaN,1374,1019,12385,562,58527
58,2020,482.51,1143.40,224.65,1088.00,2.29,11758.13,4147.59,2129.82,10605.37,...,3760,477,2079,727,NaN,1378,1008,12389,520,57658
59,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4195,480,2129,754,NaN,1380,996,12734,670,58371

In [24]:
abs_data.drop(columns=["13.2.3", "13.2.4", "13.2.5", "13.2.6", "13.2.7", "13.2.8"], inplace=True)
abs_data.head()

,Table,13.2.9,13.2.10,13.2.11,13.2.12,13.2.13,13.2.14,13.2.15,13.2.16,13.2.17,...,13.7.6,13.7.7,13.7.8,13.7.9,13.7.10,13.7.11,13.7.12,13.7.13,13.7.14,13.7.15
2,Commodity,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,...,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal,Beef and veal
3,Reporter,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,Australian Capital Territory,Australia,...,India,Japan,Mexico,New Zealand,Pakistan,Russian Federation,South Africa,United States of America,Uruguay,World
14,1976,7591.00,3331.00,11036.00,1387.00,2259.00,611.00,1616.00,0.00,28269.00,...,609,298,1079,628,NaN,NaN,537,12166,405,43549
15,1977,6689.00,2881.00,10856.00,1043.00,2084.00,543.00,1631.00,0.00,26268.00,...,615,361,990,558,NaN,NaN,580,11844,363,43783
16,1978,5844.00,2543.00,10261.00,900.00,1913.00,483.00,1738.00,0.00,24245.00,...,624,403,1038,562,NaN,NaN,629,11279,354,43541

In [25]:
beef_cattle = abs_data[["Table", "13.2.9", "13.2.10", "13.2.11", "13.2.12", "13.2.13", "13.2.14", "13.2.15", "13.2.16", "13.2.17"]]
beef_cattle.head()

,Table,13.2.9,13.2.10,13.2.11,13.2.12,13.2.13,13.2.14,13.2.15,13.2.16,13.2.17
2,Commodity,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves
3,Reporter,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,Australian Capital Territory,Australia
14,1976,7591.00,3331.00,11036.00,1387.00,2259.00,611.00,1616.00,0.00,28269.00
15,1977,6689.00,2881.00,10856.00,1043.00,2084.00,543.00,1631.00,0.00,26268.00
16,1978,5844.00,2543.00,10261.00,900.00,1913.00,483.00,1738.00,0.00,24245.00

In [26]:
final_beef_cattle = beef_cattle.rename(columns={"Table": "Year", "13.2.9": "New South Wales", "13.2.10": "Victoria", "13.2.11": "Queensland", "13.2.12": "South Australia", "13.2.13": "Western Australia", "13.2.14": "Tasmania", "13.2.15": "Northern Territory", "13.2.16": "ACT", "13.2.17": "Australia"}, inplace=False)
final_beef_cattle

,Year,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,ACT,Australia
2,Commodity,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves,Total beef cattle and calves
3,Reporter,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,Australian Capital Territory,Australia
14,1976,7591.00,3331.00,11036.00,1387.00,2259.00,611.00,1616.00,0.00,28269.00
15,1977,6689.00,2881.00,10856.00,1043.00,2084.00,543.00,1631.00,0.00,26268.00
16,1978,5844.00,2543.00,10261.00,900.00,1913.00,483.00,1738.00,0.00,24245.00
17,1979,5484.00,2643.00,9756.00,882.00,1888.00,479.00,1687.00,0.00,23373.00
18,1980,4876.00,2696.00,9359.00,904.00,1857.00,497.00,1634.00,0.00,22368.00
19,1981,4855.00,2514.00,9210.00,829.00,1772.00,466.00,1583.00,0.00,21704.00
20,1982,4545.20,1920.40,8980.70,669.90,1631.90,412.40,1547.50,10.00,19718.00
21,1983,4571.00,1952.40,8782.80,650.70,1605.80,393.60,1390.00,9.80,19356.00
22,1984,4775.30,2016.60,9051.00,683.70,1550.60,405.10,1483.80,10.90,19976.90
23,1985,4971.70,2186.40,9303.50,752.00,1567.70,426.40,1457.30,12.40,20677.40
24,1986,4445.30,2013.70,8674.80,754.90,1541.20,395.30,1438.80,11.60,19275.60
25,1987,4542.60,2038.00,8503.70,794.30,1590.20,407.70,1383.10,10.60,19270.10
26,1988,4924.00,2070.80,8682.00,798.10,1590.70,425.60,1386.50,10.40,19888.20
27,1989,5141.70,2223.70,9194.90,833.10,1564.00,435.00,1325.50,11.90,20729.80
28,1990,5310.30,2208.00,9575.20,856.60,1475.00,444.40,1351.50,10.90,21231.90
29,1991,5359.10,2152.20,9730.40,879.30,1536.30,446.70,1332.60,10.60,21447.20
30,1992,5440.00,2225.90,9593.20,961.90,1532.00,445.20,1345.20,12.00,21555.40
31,1993,6127.10,2604.00,9656.10,1055.60,1682.50,507.30,1434.20,13.10,23080.00
32,1994,5866.80,2659.20,9689.10,1063.70,1773.10,507.40,1419.40,12.50,22991.10
33,1995,6019.10,2714.10,9928.30,1069.00,1802.80,521.00,1501.60,13.40,23569.30
34,1996,6118.10,2627.00,10123.00,1023.90,1786.80,514.60,1530.20,13.10,23736.50
35,1997,5921.70,2305.60,10562.30,1051.40,1848.40,510.40,1566.40,9.60,23775.70
36,1998,5845.60,2179.80,10443.60,1005.60,1816.70,491.40,1565.90,9.40,23358.10
37,1999,5530.70,2370.60,11502.60,994.70,2058.90,410.60,1570.20,9.80,24448.00
38,2000,5786.10,2434.70,11087.60,1050.30,2001.40,426.50,1706.90,11.00,24504.40
39,2001,5592.60,2463.00,11283.80,1201.30,1979.80,431.80,1776.70,9.80,24738.70
40,2002,5419.40,2491.40,10507.40,1209.30,1815.20,481.90,1682.60,7.80,23615.10
41,2003,5416.00,2390.20,11244.80,1164.30,1962.20,495.50,1729.70,7.60,24410.20
42,2004,5335.10,2540.00,11379.60,1223.40,2010.90,498.40,1728.70,9.30,24725.30
43,2005,5862.00,2645.70,11353.90,1160.70,2275.20,500.60,1798.20,9.20,25605.50
44,2006,5609.00,2575.20,11494.90,1066.80,2222.80,481.20,1912.20,11.00,25373.20
45,2007,5330.40,2254.30,11730.60,965.80,2012.50,443.60,2040.80,6.00,24784.10
46,2008,5533.10,2234.30,12151.40,1042.20,2220.30,425.70,1680.50,7.00,25294.50
47,2009,5107.10,2079.50,11193.30,903.90,2206.20,445.80,2065.70,6.30,24007.70
48,2010,5383.93,2365.85,12449.63,1109.64,1954.38,466.58,2197.36,8.81,25936.20
49,2011,5497.05,2362.08,11989.53,1204.50,1956.63,472.22,2195.22,8.01,25685.23
50,2012,5593.04,2427.18,12628.33,1193.45,1883.24,522.24,2199.86,9.56,26456.90
51,2013,5325.21,2428.17,12754.97,1109.84,1972.76,534.46,2164.33,6.03,26295.78
52,2014,5278.78,2300.61,11178.49,1014.87,2242.22,466.38,2114.57,6.37,24602.28
53,2015,4674.55,1819.06,10390.12,913.89,1878.47,385.86,2238.35,5.97,22306.28
54,2016,4992.27,1980.66,10992.60,956.15,1992.69,461.42,2188.59,5.39,23569.77
55,2017,4425.55,2064.21,11909.95,910.04,1900.98,432.63,2119.25,5.78,23768.38
56,2018,3780.35,2106.24,11156.29,880.72,1877.68,430.90,2146.93,3.00,22382.09
57,2019,3602.63,2045.37,10381.26,908.14,1922.97,480.25,1798.85,2.37,21141.84
58,2020,4147.59,2129.82,10605.37,936.72,2022.72,470.46,1731.71,3.96,22048.33
59,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22750.00

In [27]:
final_beef_cattle=final_beef_cattle.drop(final_beef_cattle.index[0])
final_beef_cattle

,Year,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,ACT,Australia
3,Reporter,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,Australian Capital Territory,Australia
14,1976,7591.00,3331.00,11036.00,1387.00,2259.00,611.00,1616.00,0.00,28269.00
15,1977,6689.00,2881.00,10856.00,1043.00,2084.00,543.00,1631.00,0.00,26268.00
16,1978,5844.00,2543.00,10261.00,900.00,1913.00,483.00,1738.00,0.00,24245.00
17,1979,5484.00,2643.00,9756.00,882.00,1888.00,479.00,1687.00,0.00,23373.00
18,1980,4876.00,2696.00,9359.00,904.00,1857.00,497.00,1634.00,0.00,22368.00
19,1981,4855.00,2514.00,9210.00,829.00,1772.00,466.00,1583.00,0.00,21704.00
20,1982,4545.20,1920.40,8980.70,669.90,1631.90,412.40,1547.50,10.00,19718.00
21,1983,4571.00,1952.40,8782.80,650.70,1605.80,393.60,1390.00,9.80,19356.00
22,1984,4775.30,2016.60,9051.00,683.70,1550.60,405.10,1483.80,10.90,19976.90
23,1985,4971.70,2186.40,9303.50,752.00,1567.70,426.40,1457.30,12.40,20677.40
24,1986,4445.30,2013.70,8674.80,754.90,1541.20,395.30,1438.80,11.60,19275.60
25,1987,4542.60,2038.00,8503.70,794.30,1590.20,407.70,1383.10,10.60,19270.10
26,1988,4924.00,2070.80,8682.00,798.10,1590.70,425.60,1386.50,10.40,19888.20
27,1989,5141.70,2223.70,9194.90,833.10,1564.00,435.00,1325.50,11.90,20729.80
28,1990,5310.30,2208.00,9575.20,856.60,1475.00,444.40,1351.50,10.90,21231.90
29,1991,5359.10,2152.20,9730.40,879.30,1536.30,446.70,1332.60,10.60,21447.20
30,1992,5440.00,2225.90,9593.20,961.90,1532.00,445.20,1345.20,12.00,21555.40
31,1993,6127.10,2604.00,9656.10,1055.60,1682.50,507.30,1434.20,13.10,23080.00
32,1994,5866.80,2659.20,9689.10,1063.70,1773.10,507.40,1419.40,12.50,22991.10
33,1995,6019.10,2714.10,9928.30,1069.00,1802.80,521.00,1501.60,13.40,23569.30
34,1996,6118.10,2627.00,10123.00,1023.90,1786.80,514.60,1530.20,13.10,23736.50
35,1997,5921.70,2305.60,10562.30,1051.40,1848.40,510.40,1566.40,9.60,23775.70
36,1998,5845.60,2179.80,10443.60,1005.60,1816.70,491.40,1565.90,9.40,23358.10
37,1999,5530.70,2370.60,11502.60,994.70,2058.90,410.60,1570.20,9.80,24448.00
38,2000,5786.10,2434.70,11087.60,1050.30,2001.40,426.50,1706.90,11.00,24504.40
39,2001,5592.60,2463.00,11283.80,1201.30,1979.80,431.80,1776.70,9.80,24738.70
40,2002,5419.40,2491.40,10507.40,1209.30,1815.20,481.90,1682.60,7.80,23615.10
41,2003,5416.00,2390.20,11244.80,1164.30,1962.20,495.50,1729.70,7.60,24410.20
42,2004,5335.10,2540.00,11379.60,1223.40,2010.90,498.40,1728.70,9.30,24725.30
43,2005,5862.00,2645.70,11353.90,1160.70,2275.20,500.60,1798.20,9.20,25605.50
44,2006,5609.00,2575.20,11494.90,1066.80,2222.80,481.20,1912.20,11.00,25373.20
45,2007,5330.40,2254.30,11730.60,965.80,2012.50,443.60,2040.80,6.00,24784.10
46,2008,5533.10,2234.30,12151.40,1042.20,2220.30,425.70,1680.50,7.00,25294.50
47,2009,5107.10,2079.50,11193.30,903.90,2206.20,445.80,2065.70,6.30,24007.70
48,2010,5383.93,2365.85,12449.63,1109.64,1954.38,466.58,2197.36,8.81,25936.20
49,2011,5497.05,2362.08,11989.53,1204.50,1956.63,472.22,2195.22,8.01,25685.23
50,2012,5593.04,2427.18,12628.33,1193.45,1883.24,522.24,2199.86,9.56,26456.90
51,2013,5325.21,2428.17,12754.97,1109.84,1972.76,534.46,2164.33,6.03,26295.78
52,2014,5278.78,2300.61,11178.49,1014.87,2242.22,466.38,2114.57,6.37,24602.28
53,2015,4674.55,1819.06,10390.12,913.89,1878.47,385.86,2238.35,5.97,22306.28
54,2016,4992.27,1980.66,10992.60,956.15,1992.69,461.42,2188.59,5.39,23569.77
55,2017,4425.55,2064.21,11909.95,910.04,1900.98,432.63,2119.25,5.78,23768.38
56,2018,3780.35,2106.24,11156.29,880.72,1877.68,430.90,2146.93,3.00,22382.09
57,2019,3602.63,2045.37,10381.26,908.14,1922.97,480.25,1798.85,2.37,21141.84
58,2020,4147.59,2129.82,10605.37,936.72,2022.72,470.46,1731.71,3.96,22048.33
59,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22750.00

In [28]:
final_beef_cattle=final_beef_cattle.drop(final_beef_cattle.index[0])
final_beef_cattle

,Year,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,ACT,Australia
14,1976,7591.00,3331.00,11036.00,1387.00,2259.00,611.00,1616.00,0.00,28269.00
15,1977,6689.00,2881.00,10856.00,1043.00,2084.00,543.00,1631.00,0.00,26268.00
16,1978,5844.00,2543.00,10261.00,900.00,1913.00,483.00,1738.00,0.00,24245.00
17,1979,5484.00,2643.00,9756.00,882.00,1888.00,479.00,1687.00,0.00,23373.00
18,1980,4876.00,2696.00,9359.00,904.00,1857.00,497.00,1634.00,0.00,22368.00
19,1981,4855.00,2514.00,9210.00,829.00,1772.00,466.00,1583.00,0.00,21704.00
20,1982,4545.20,1920.40,8980.70,669.90,1631.90,412.40,1547.50,10.00,19718.00
21,1983,4571.00,1952.40,8782.80,650.70,1605.80,393.60,1390.00,9.80,19356.00
22,1984,4775.30,2016.60,9051.00,683.70,1550.60,405.10,1483.80,10.90,19976.90
23,1985,4971.70,2186.40,9303.50,752.00,1567.70,426.40,1457.30,12.40,20677.40
24,1986,4445.30,2013.70,8674.80,754.90,1541.20,395.30,1438.80,11.60,19275.60
25,1987,4542.60,2038.00,8503.70,794.30,1590.20,407.70,1383.10,10.60,19270.10
26,1988,4924.00,2070.80,8682.00,798.10,1590.70,425.60,1386.50,10.40,19888.20
27,1989,5141.70,2223.70,9194.90,833.10,1564.00,435.00,1325.50,11.90,20729.80
28,1990,5310.30,2208.00,9575.20,856.60,1475.00,444.40,1351.50,10.90,21231.90
29,1991,5359.10,2152.20,9730.40,879.30,1536.30,446.70,1332.60,10.60,21447.20
30,1992,5440.00,2225.90,9593.20,961.90,1532.00,445.20,1345.20,12.00,21555.40
31,1993,6127.10,2604.00,9656.10,1055.60,1682.50,507.30,1434.20,13.10,23080.00
32,1994,5866.80,2659.20,9689.10,1063.70,1773.10,507.40,1419.40,12.50,22991.10
33,1995,6019.10,2714.10,9928.30,1069.00,1802.80,521.00,1501.60,13.40,23569.30
34,1996,6118.10,2627.00,10123.00,1023.90,1786.80,514.60,1530.20,13.10,23736.50
35,1997,5921.70,2305.60,10562.30,1051.40,1848.40,510.40,1566.40,9.60,23775.70
36,1998,5845.60,2179.80,10443.60,1005.60,1816.70,491.40,1565.90,9.40,23358.10
37,1999,5530.70,2370.60,11502.60,994.70,2058.90,410.60,1570.20,9.80,24448.00
38,2000,5786.10,2434.70,11087.60,1050.30,2001.40,426.50,1706.90,11.00,24504.40
39,2001,5592.60,2463.00,11283.80,1201.30,1979.80,431.80,1776.70,9.80,24738.70
40,2002,5419.40,2491.40,10507.40,1209.30,1815.20,481.90,1682.60,7.80,23615.10
41,2003,5416.00,2390.20,11244.80,1164.30,1962.20,495.50,1729.70,7.60,24410.20
42,2004,5335.10,2540.00,11379.60,1223.40,2010.90,498.40,1728.70,9.30,24725.30
43,2005,5862.00,2645.70,11353.90,1160.70,2275.20,500.60,1798.20,9.20,25605.50
44,2006,5609.00,2575.20,11494.90,1066.80,2222.80,481.20,1912.20,11.00,25373.20
45,2007,5330.40,2254.30,11730.60,965.80,2012.50,443.60,2040.80,6.00,24784.10
46,2008,5533.10,2234.30,12151.40,1042.20,2220.30,425.70,1680.50,7.00,25294.50
47,2009,5107.10,2079.50,11193.30,903.90,2206.20,445.80,2065.70,6.30,24007.70
48,2010,5383.93,2365.85,12449.63,1109.64,1954.38,466.58,2197.36,8.81,25936.20
49,2011,5497.05,2362.08,11989.53,1204.50,1956.63,472.22,2195.22,8.01,25685.23
50,2012,5593.04,2427.18,12628.33,1193.45,1883.24,522.24,2199.86,9.56,26456.90
51,2013,5325.21,2428.17,12754.97,1109.84,1972.76,534.46,2164.33,6.03,26295.78
52,2014,5278.78,2300.61,11178.49,1014.87,2242.22,466.38,2114.57,6.37,24602.28
53,2015,4674.55,1819.06,10390.12,913.89,1878.47,385.86,2238.35,5.97,22306.28
54,2016,4992.27,1980.66,10992.60,956.15,1992.69,461.42,2188.59,5.39,23569.77
55,2017,4425.55,2064.21,11909.95,910.04,1900.98,432.63,2119.25,5.78,23768.38
56,2018,3780.35,2106.24,11156.29,880.72,1877.68,430.90,2146.93,3.00,22382.09
57,2019,3602.63,2045.37,10381.26,908.14,1922.97,480.25,1798.85,2.37,21141.84
58,2020,4147.59,2129.82,10605.37,936.72,2022.72,470.46,1731.71,3.96,22048.33
59,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22750.00

In [29]:
beef_cattle_analyse = final_beef_cattle.dropna(how="any")
beef_cattle_analyse

,Year,New South Wales,Victoria,Queensland,South Australia,Western Australia,Tasmania,Northern Territory,ACT,Australia
14,1976,7591.00,3331.00,11036.00,1387.00,2259.00,611.00,1616.00,0.00,28269.00
15,1977,6689.00,2881.00,10856.00,1043.00,2084.00,543.00,1631.00,0.00,26268.00
16,1978,5844.00,2543.00,10261.00,900.00,1913.00,483.00,1738.00,0.00,24245.00
17,1979,5484.00,2643.00,9756.00,882.00,1888.00,479.00,1687.00,0.00,23373.00
18,1980,4876.00,2696.00,9359.00,904.00,1857.00,497.00,1634.00,0.00,22368.00
19,1981,4855.00,2514.00,9210.00,829.00,1772.00,466.00,1583.00,0.00,21704.00
20,1982,4545.20,1920.40,8980.70,669.90,1631.90,412.40,1547.50,10.00,19718.00
21,1983,4571.00,1952.40,8782.80,650.70,1605.80,393.60,1390.00,9.80,19356.00
22,1984,4775.30,2016.60,9051.00,683.70,1550.60,405.10,1483.80,10.90,19976.90
23,1985,4971.70,2186.40,9303.50,752.00,1567.70,426.40,1457.30,12.40,20677.40
24,1986,4445.30,2013.70,8674.80,754.90,1541.20,395.30,1438.80,11.60,19275.60
25,1987,4542.60,2038.00,8503.70,794.30,1590.20,407.70,1383.10,10.60,19270.10
26,1988,4924.00,2070.80,8682.00,798.10,1590.70,425.60,1386.50,10.40,19888.20
27,1989,5141.70,2223.70,9194.90,833.10,1564.00,435.00,1325.50,11.90,20729.80
28,1990,5310.30,2208.00,9575.20,856.60,1475.00,444.40,1351.50,10.90,21231.90
29,1991,5359.10,2152.20,9730.40,879.30,1536.30,446.70,1332.60,10.60,21447.20
30,1992,5440.00,2225.90,9593.20,961.90,1532.00,445.20,1345.20,12.00,21555.40
31,1993,6127.10,2604.00,9656.10,1055.60,1682.50,507.30,1434.20,13.10,23080.00
32,1994,5866.80,2659.20,9689.10,1063.70,1773.10,507.40,1419.40,12.50,22991.10
33,1995,6019.10,2714.10,9928.30,1069.00,1802.80,521.00,1501.60,13.40,23569.30
34,1996,6118.10,2627.00,10123.00,1023.90,1786.80,514.60,1530.20,13.10,23736.50
35,1997,5921.70,2305.60,10562.30,1051.40,1848.40,510.40,1566.40,9.60,23775.70
36,1998,5845.60,2179.80,10443.60,1005.60,1816.70,491.40,1565.90,9.40,23358.10
37,1999,5530.70,2370.60,11502.60,994.70,2058.90,410.60,1570.20,9.80,24448.00
38,2000,5786.10,2434.70,11087.60,1050.30,2001.40,426.50,1706.90,11.00,24504.40
39,2001,5592.60,2463.00,11283.80,1201.30,1979.80,431.80,1776.70,9.80,24738.70
40,2002,5419.40,2491.40,10507.40,1209.30,1815.20,481.90,1682.60,7.80,23615.10
41,2003,5416.00,2390.20,11244.80,1164.30,1962.20,495.50,1729.70,7.60,24410.20
42,2004,5335.10,2540.00,11379.60,1223.40,2010.90,498.40,1728.70,9.30,24725.30
43,2005,5862.00,2645.70,11353.90,1160.70,2275.20,500.60,1798.20,9.20,25605.50
44,2006,5609.00,2575.20,11494.90,1066.80,2222.80,481.20,1912.20,11.00,25373.20
45,2007,5330.40,2254.30,11730.60,965.80,2012.50,443.60,2040.80,6.00,24784.10
46,2008,5533.10,2234.30,12151.40,1042.20,2220.30,425.70,1680.50,7.00,25294.50
47,2009,5107.10,2079.50,11193.30,903.90,2206.20,445.80,2065.70,6.30,24007.70
48,2010,5383.93,2365.85,12449.63,1109.64,1954.38,466.58,2197.36,8.81,25936.20
49,2011,5497.05,2362.08,11989.53,1204.50,1956.63,472.22,2195.22,8.01,25685.23
50,2012,5593.04,2427.18,12628.33,1193.45,1883.24,522.24,2199.86,9.56,26456.90
51,2013,5325.21,2428.17,12754.97,1109.84,1972.76,534.46,2164.33,6.03,26295.78
52,2014,5278.78,2300.61,11178.49,1014.87,2242.22,466.38,2114.57,6.37,24602.28
53,2015,4674.55,1819.06,10390.12,913.89,1878.47,385.86,2238.35,5.97,22306.28
54,2016,4992.27,1980.66,10992.60,956.15,1992.69,461.42,2188.59,5.39,23569.77
55,2017,4425.55,2064.21,11909.95,910.04,1900.98,432.63,2119.25,5.78,23768.38
56,2018,3780.35,2106.24,11156.29,880.72,1877.68,430.90,2146.93,3.00,22382.09
57,2019,3602.63,2045.37,10381.26,908.14,1922.97,480.25,1798.85,2.37,21141.84
58,2020,4147.59,2129.82,10605.37,936.72,2022.72,470.46,1731.71,3.96,22048.33

In [30]:
beef_cattle_analyse.columns.to_list()

['Year',
 'New South Wales',
 'Victoria',
 'Queensland',
 'South Australia',
 'Western Australia',
 'Tasmania',
 'Northern Territory',
 'ACT',
 'Australia']

In [31]:
qld_cattle = beef_cattle_analyse[["Year", "Queensland"]]
qld_cattle

    Year Queensland
14  1976   11036.00
15  1977   10856.00
16  1978   10261.00
17  1979    9756.00
18  1980    9359.00
19  1981    9210.00
20  1982    8980.70
21  1983    8782.80
22  1984    9051.00
23  1985    9303.50
24  1986    8674.80
25  1987    8503.70
26  1988    8682.00
27  1989    9194.90
28  1990    9575.20
29  1991    9730.40
30  1992    9593.20
31  1993    9656.10
32  1994    9689.10
33  1995    9928.30
34  1996   10123.00
35  1997   10562.30
36  1998   10443.60
37  1999   11502.60
38  2000   11087.60
39  2001   11283.80
40  2002   10507.40
41  2003   11244.80
42  2004   11379.60
43  2005   11353.90
44  2006   11494.90
45  2007   11730.60
46  2008   12151.40
47  2009   11193.30
48  2010   12449.63
49  2011   11989.53
50  2012   12628.33
51  2013   12754.97
52  2014   11178.49
53  2015   10390.12
54  2016   10992.60
55  2017   11909.95
56  2018   11156.29
57  2019   10381.26
58  2020   10605.37

In [32]:
qld_cattle.to_csv("qld_cattle_counts.csv")